### ISSUE TITLE
Lenovo Miix 3 830 problem

### ISSUE THREAD

**Issue by OggiCZ** [ouija/android-x86-toshiba_encore2#3]
Hello, 
first off all i wanna thank you for your incredible work! 
I got this tablet ( same specs as WT-10A ) but i have a little problem with gyroscope module. Not working, everything else working good ( low volume on speaker, but this is maybe normal ). 

In droid senzor app i see SMO 8500 but i dont know if that is your sensor or mine.

Im really newbie here and dont know how to check it.

On previous attempt ( Phoenix os ) gyro work, but in reverse orientation.

Do you help me resolve that? Maybe you got better drivers for WiFi and bluetooth too ( same chip ). 

Thank you 

Sincerely John from Czech Republic.

**Comment by ouija** [comment]
Sorry for the late reply, but I'm not actively support this project at the moment.   You can find support for gyro/rotation issues on the [Android-x96 Google Group](https://groups.google.com/g/android-x86)

Essentially you need to figure out what settings work based on your accelerometer model and add an entry to the `init_hal_sensors ` section of the `/system/init.sh` script that targets your device and initializes the device properly.
